### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by wilfried18** [cubanpit/cleanupdate#7]
I would like to know how to use your script (no info was about the least I found)
Thanks for your script

**Comment by cubanpit** [comment]
You can install it with an AUR helper (like _yaourt_ : `yaourt -S cleanupdate-git`) and call it with `cleanupdate` or clicking on it in your application menu.
Otherwise you can copy the script manually inside a file `cleanupdate.sh`, give it necessary permissions with `chmod +x cleanupdate.sh` and call it with `./cleanupdate.sh`.
Thanks for the feedback, I'll add some documentation about this issue.

**Comment by cubanpit** [comment]
Commit [`9acbad0`](https://github.com/cubanpit/cleanupdate/commit/9acbad08cf3b9ce4ba2e512ce478004a1c3366a2) should have solved this issue completely.
