### ISSUE TITLE
Remove yaourt and pacaur support

### ISSUE THREAD

**Issue by francoism90** [cubanpit/cleanupdate#8]
https://wiki.archlinux.org/index.php/AUR_helpers#Discontinued_or_problematic

I suggest to completely remove yaourt and pacaur support from this script.
Both are abandoned and should not be used anymore if one wants to keep their systems safe.

Thanks.

**Comment by cubanpit** [comment]
I am evaluating the removal of those helpers since months but they are very common, at the moment I prefer to keep them as last elements in priority.
Also `trizen` and `aurman` are not the best choices.
In my opinion users are responsible for their AUR helper of choice, I am not really "strict" about supporting them in cleanupdate.

Thanks for your interest in cleanupdate
